### ISSUE TITLE
Can't delete cheese in first rank after other cheeses have been placed

### ISSUE THREAD

**Issue by danseery** [kditraglia/TowerDefense#6]
https://www.youtube.com/watch?v=DEnQLFl78mI

**Comment by kditraglia** [comment]
So this problems stems from a hack that I put in to try to alleviate the other problem.  If I take the hack out it makes the other problem worse but fixes this problem (for each 'leg' of their path finding, I disable the start nodes from possibly being cheese).  This causes cheeses on the first rank to be handled differently.

I'm going to remove the hack for now, which basically means enemies will only ever need to get 1 cheese (they will hit it the number of times of cheese on the map, but they won't go for the other ones).  It will fix this issue and make the other worse, which I'll work on next.

**Comment by kditraglia** [comment]
Fixed in: 5def13af3a3dddbb248cd5c9a2a28cbe34423812
